---
- name: group module dmeo
  hosts: all
  become: true
  vars:
    mygroup: "myexample"
  tasks:
    - name: create group
      ansible.builtin.group:
        name: "{{ mygroup }}"
        state: present
      tags: creategroup

    - name: delete group
      ansible.builtin.group:
        name: "{{ mygroup }}"
        state: absent
      tags: deletegroup
