---
- name: DBserver setup
  hosts: dbservers
  become: yes
#  vars:
#    dbname: electric
#    dbuser: current
#    dbpass: tesla
  tasks:
    - name: variable details1
      debug:
        msg: "The dbname is {{dbname}}"

    - name: variable details2
      debug:
        var: dbuser

    - name: Install mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    - name: Install pymysql
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present

    - name: Start mariadb service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database with name "{{dbname}}"
      community.mysql.mysql_db:
        login_unix_socket: /var/lib/mysql/mysql.sock
        name: "{{dbname}}"
        state: present

    - name: Create database user with name "{{dbuser}}" and password "{{dbpass}}" with all database privileges
      community.mysql.mysql_user:
        login_unix_socket: /var/lib/mysql/mysql.sock
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
      register: dbout

    - name: print dbout variable
      debug:
        var: dbout
