---
- name: unarchive module demo
  hosts: all
  become: false
  vars:
    myurl: "https://github.com/lucab85/ansible-pilot/archive/refs/heads/master.zip"
  tasks:
    - name: extractor present in centos
      ansible.builtin.yum:
        name:
          - unzip
          - tar
        state: present
      become: true
      when: ansible_distribution == "CentOS"

    - name: extractor present in ubuntu
      ansible.builtin.apt:
        name:
          - unzip
          - tar
        state: present
      become: true
      when: ansible_distribution == "Ubuntu"

    - name: extract archive
      ansible.builtin.unarchive:
        src: "{{ myurl }}"
        dest: "/home/vagrant/"
        remote_src: true
        validate_certs: true
