---
- name: Delete a Branch Using GitHub API
  hosts: localhost
  vars:
    github_username: "vishnuteja407"
    github_repo: "Ansible_devops"
    github_token: "{{ lookup('env', 'ANSIBLE_TOKEN') }}" 
    branch_to_delete: "feature/ansible-develop" 
  tasks:
    - name: Get the SHA of the Branch
      uri:
        url: "https://api.github.com/repos/{{ github_username }}/{{ github_repo }}/git/refs/heads/{{ branch_to_delete }}"
        method: GET
        headers:
          Authorization: "token {{ github_token }}"
      register: branch_info
      failed_when: branch_info.status not in [200, 201, 204]

    - name: Delete the Branch
      uri:
        url: "https://api.github.com/repos/{{ github_username }}/{{ github_repo }}/git/refs/heads/{{ branch_to_delete }}"
        method: DELETE
        headers:
          Authorization: "token {{ github_token }}"
      register: delete_branch
      failed_when: delete_branch.status not in [200, 201, 204]
      when: branch_info.status == 200

