---
- name: Delete GitHub Repository
  hosts: localhost
  gather_facts: no
  vars:
    github_username: "vishnuteja407"
    repo_name: "Ansible_devops"  
    github_token: "{{ lookup('env', 'ANSIBLE_TOKEN') }}" 
  tasks:
    - name: Delete Repository
      uri:
        url: https://api.github.com/repos/{{ github_username }}/{{ repo_name }}
        method: DELETE
        headers:
          Authorization: "token {{ github_token }}"
        return_content: yes
      register: response
      failed_when: response.status not in [200, 201, 204]

    - name: Debug Response
      debug:
        var: response

