- name: blockinfile module demo
  hosts: web01
  become: yes
  tasks:
    - name: Generate /etc/hosts file
      ansible.builtin.blockinfile:
        state: present
        dest: /etc/hosts
        content: |
          192.168.10.21 control
