---
- name: Test SSH connection to GitHub
  hosts: web03
  become: yes
  tasks:
    - name: Debug SSH Connection
      command: ssh -v -T git@github.com
      environment:
        ANSIBLE_SSH_ARGS: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
      register: ssh_result
      ignore_errors: yes

    - name: validate of ssh is success
      assert:
        that: 
          - "'successfully authenticated' in ssh_result.stderr"

