---
- name: copy and template module demo
  hosts: all
  vars:
    fruit: "banana"
    output: "output.txt"
    fruit2: "apple" 
  tasks:
    - name: write to file
      ansible.builtin.copy:
        content: "{{ fruit }}"
        dest: "{{ output }}"
 
    - name: write using template module
      ansible.builtin.template:
        src: "mytemplates.j2"
        dest: "{{ output }}"
