---
- name: cron module demo
  hosts: all
  tasks:
    - name: "example cronjob"
      ansible.builtin.cron:
        name: "test"
        state: present
        minute: "*/2"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: 'logger "ansible practice"'

    - name: remove cron job
      cron:
        name: "test"
        state: absent
