---
- name: debug module demo
  hosts: localhost
  vars:
    variable1: |
      exactly as you see 
      will appear these three
      lines of poetry
    variable2: >
      this is really single line
      of text
      despite appear
      in multiple lines
  tasks:
    - name: print variable1
      ansible.builtin.debug:
        msg: "{{ variable1.split('\n') }}"

    - name: print variable2
      ansible.builtin.debug:
        var: variable2
