---
- name: Remote env demo
  hosts: all
  gather_facts: false
  environment:
    EXAMPLE: test1

  tasks:
    - name: Display example
      ansible.builtin.command: "echo $EXAMPLE"

    - name: Display example
      ansible.builtin.command: "echo $EXAMPLE"
      environment:
        EXAMPLE: test2
