---
- name: root login enabled
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: ssh permitrootlogin
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regex: '^PermitRootLogin'
        line: 'PermitRootLogin yes'
        state: present
      notify: ssh restart

  handlers:
    - name: ssh restart
      ansible.builtin.service:
        name: sshd
        state: restarted





# ansible-playbook root_login_enable.yaml --check --diff
