---
- name: modprobe module demo
  hosts: localhost
  vars:
    module_name: "dummy"
    ansible_connection: local
  tasks:
    - name: load the module
      community.general.modprobe:
        name: "{{ module_name }}"
        state: present
