---
- name: DBserver setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    - name: Install pymysql
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present

    - name: Start mariadb service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database with name 'accounts'
      community.mysql.mysql_db:
        login_unix_socket: /var/lib/mysql/mysql.sock
        name: accounts
        state: present

    - name: Create database user with name 'vprofile' and password '12345' with all database privileges
      community.mysql.mysql_user:
        login_unix_socket: /var/lib/mysql/mysql.sock
        name: vprofile
        password: 'admin123'
        priv: '*.*:ALL'
        state: present
