---
- name: setup webserver with vhost
  hosts: web01
  become: true
  vars:
    app_user: "apache"
    http_host: "practice.com"
    http_conf: "practice.com.conf"
    http_port: "80"
  tasks:
    - name: httpd installed
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: document root exist
      ansible.builtin.file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: "0755"
        setype: "httpd_sys_content_t"

    - name: custom index.tml
      copy:
        dest: "/var/www/{{ http_host }}/index.html"
        content: >
          Custom web page
          using vhost

    - name: setup apache virtualhost
      ansible.builtin.template:
        src: "templates/apache.conf.j2"
        dest: "/etc/httpd/conf.d/{{ http_conf }}"

    - name: httpd service enabled
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    - name: open firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true
