---
# https://man7.org/linux/man-pages/man8/selinux.8.html
# vim  /etc/sysconfig/selinux
# getenforce
# sestatus
- name: selinux module demo
  hosts: all
  become: true
  vars:
    selinux_state: "enforcing"
    selinux_policy: "targeted"

  tasks:
    - name: Install the required library
      package:
        name: 
          - selinux-utils
          - policycoreutils
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: SELinux policy and state
      ansible.posix.selinux:
        state: "{{ selinux_state }}"
        policy: "{{ selinux_policy }}"
      notify: relabel and reboot
      when: ansible_os_family == "RedHat"

  handlers:
    - name: relabel files on next boot
      ansible.builtin.file:
        path: "/.autorelabel"
        state: touch
      when:
        - selinux_state != "disabled"
      listen: relabel and reboot

    - name: reboot host
      ansible.builtin.reboot:
      listen: relabel and reboot

