---
- name: syncroniza module demo
  hosts: web02
  become: false
  vars:
    source: "/home/vagrant/vprofile/filePermissions"
    destination: "Ansible-backup"
  tasks:
    - name: rsync installed
      ansible.builtin.package:
        name: rsync
        state: present
      become: true
   
    - name: data sync
      ansible.posix.synchronize:
        src: "{{ source }}"
        dest: "{{ destination }}"
          
